### ISSUE TITLE
iOS Web Credentials

### ISSUE THREAD

**Issue by acurrieclark** [AyogoHealth/cordova-plugin-app-scope#9]
The link you provide for "Setting Up an App’s Associated Domains" on iOS seems to suggest that a `webcredentials:example.com` entry be listed in the Associated Domains field.

Following installation, I found an entry for `applinks` and `activitycontinuation`. I have manually added `webcredentials`, but wondered if it should be added automatically?

**Comment by dpogue** [comment]
hmm, I don't recall seeing `webcredentials` in the docs before, but it looks like they've shuffled things around. [This](https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/enabling_universal_links) is the page I thought it was linking to.

However, if we can set it up to allow sharing credentials with Safari, it's probably worth adding to improve the overall integration with the web.

Note that it will also need to be set up in the apple-app-site-association file on the server.

**Comment by dpogue** [comment]
Released in cordova-plugin-app-scope@1.1.0 :)

**Comment by acurrieclark** [comment]
Perfect! Was about to submit a pull request. Thanks for the swift turnaround.
